# Generated by Django 5.2 on 2025-05-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_middle_name_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pet_age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вік улюбленця'),
        ),
        migrations.AddField(
            model_name='user',
            name='pet_breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Порода улюбленця'),
        ),
        migrations.AddField(
            model_name='user',
            name='pet_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Ім'я улюбленця"),
        ),
    ]
