# Generated by Django 5.2 on 2025-05-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_pet_age_user_pet_breed_user_pet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pet_age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pet_breed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pet_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
