# Generated by Django 5.2 on 2025-05-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_city_user_postal_code_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_image', verbose_name='Фото користувача'),
        ),
    ]
