# Generated by Django 5.2 on 2025-05-23 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pets_image', verbose_name='Фото улюбленця')),
                ('age_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вік (повних років)')),
                ('age_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вік (місяців, до 11)')),
                ('species', models.CharField(help_text='Наприклад: Собака, Кіт, Папуга', max_length=100, verbose_name='Вид тварини')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Порода')),
                ('health_features', models.TextField(blank=True, null=True, verbose_name="Особливості здоров'я та характеру")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Улюбленець',
                'verbose_name_plural': 'Улюбленці',
                'ordering': ['name'],
            },
        ),
    ]
