# Generated by Django 5.2 on 2025-05-23 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Вкажіть вагу в кілограмах, наприклад: 5.25', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Вага (кг)'),
        ),
    ]
