# Generated by Django 5.2 on 2025-05-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Самець', 'MALE'), ('Самиця', 'FEMALE'), ('Невідомо', 'UNKNOWN')], max_length=10, null=True, verbose_name='Стать'),
        ),
    ]
