# Generated by Django 5.2 on 2025-05-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Самець', 'Самець'), ('Самиця', 'Самиця'), ('Невідомо', 'Невідомо')], max_length=10, null=True, verbose_name='Стать'),
        ),
    ]
