# Generated by Django 5.2 on 2025-05-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL-фрагмент (слаг)')),
                ('short_description', models.CharField(max_length=255, verbose_name='Короткий опис')),
                ('full_description', models.TextField(verbose_name='Повний опис (для деталей)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services_images/', verbose_name='Зображення')),
                ('icon_class', models.CharField(default='fas fa-clinic-medical', max_length=100, verbose_name='Клас іконки Font Awesome (напр., fas fa-paw)')),
                ('icon_color_class', models.CharField(default='text-indigo-500', max_length=50, verbose_name='Клас кольору іконки (напр., text-pink-500)')),
                ('button_text', models.CharField(default='Записатися', max_length=50, verbose_name='Текст кнопки')),
                ('button_icon_class', models.CharField(default='fas fa-calendar-check', max_length=50, verbose_name='Клас іконки для кнопки (напр., fas fa-cut)')),
                ('button_color_class', models.CharField(default='bg-indigo-600 hover:bg-indigo-700 focus:ring-indigo-500', max_length=100, verbose_name='CSS класи для кольору кнопки')),
                ('available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['name'],
            },
        ),
    ]
