# Generated by Django 5.2 on 2025-04-25 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
