# Generated by Django 5.2 on 2025-05-20 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_datetime', models.DateTimeField(verbose_name='Бажана дата та час')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки клієнта')),
                ('status', models.CharField(choices=[('pending', 'Очікується підтвердження'), ('confirmed', 'Підтверджено'), ('cancelled_by_user', 'Скасовано клієнтом'), ('cancelled_by_clinic', 'Скасовано клінікою'), ('completed', 'Завершено')], default='pending', max_length=25, verbose_name='Статус запису')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення запису')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.service', verbose_name='Послуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Запис на послугу',
                'verbose_name_plural': 'Записи на послуги',
                'ordering': ['-requested_datetime', '-created_at'],
            },
        ),
    ]
